// test/load/soak.test.ts
// Proves the number printed on the sheet: 5,000 events through randomly failing
// targets, nothing lost, nothing duplicated.
//
// 5,000 rather than more because the failure pattern is `i % 7`, `i % 11` and
// `i % 13`, and those are coprime: every combination of reachable targets has been
// seen once after 1,001 events. Five full cycles is the coverage; anything beyond
// that is the same matrix again at the price of CI minutes.
//
// Runs on recorded extractions, never on live model calls — the run would otherwise
// cost real money every time CI fires.
import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { writeFileSync } from 'node:fs';
import { startHarness } from '../integration/harness';

const EVENTS = 5_000;

let harness: Awaited<ReturnType<typeof startHarness>>;

beforeAll(async () => { harness = await startHarness(); }, 180_000);
afterAll(async () => { await harness.stop(); });

describe('soak', () => {
  it('loses nothing and duplicates nothing across 5,000 events', async () => {
    const started = Date.now();

    for (let i = 0; i < EVENTS; i++) {
      // Deterministic pseudo-chaos so a failure is reproducible.
      harness.targets.hubspot.reachable = i % 7 !== 0;
      harness.targets.ledger.reachable = i % 11 !== 0;
      harness.targets.slack.reachable = i % 13 !== 0;

      await harness.intake.accept({
        externalId: `soak_${i}`,
        kind: 'order.placed',
        payload: { customerName: 'Soak', customerEmail: 's@example.com', totalCents: 100 },
        targets: ['hubspot', 'stripe', 'ledger', 'slack'],
      });

      // Replay every tenth event, as a duplicated webhook would.
      if (i % 10 === 0) {
        await harness.intake.accept({
          externalId: `soak_${i}`,
          kind: 'order.placed',
          payload: { customerName: 'Soak', customerEmail: 's@example.com', totalCents: 100 },
          targets: ['hubspot', 'stripe', 'ledger', 'slack'],
        });
      }
      if (i % 50 === 0) await harness.worker.tick();
    }

    for (const target of Object.values(harness.targets)) target.reachable = true;
    await harness.drain(5_000);

    const { rows: events } = await harness.pool.query<{ n: string }>(
      'SELECT count(*) AS n FROM events',
    );
    const { rows: states } = await harness.pool.query<{ state: string; n: string }>(
      'SELECT state, count(*) AS n FROM deliveries GROUP BY state',
    );
    const byState = Object.fromEntries(states.map((r) => [r.state, Number(r.n)]));

    // Every target saw each event at most once — the fakes are idempotent by key,
    // so a second call would show up as a shorter received list than delivery count.
    const { rows: dupes } = await harness.pool.query<{ n: string }>(
      `SELECT count(*) AS n FROM (
         SELECT event_id, target FROM deliveries
          GROUP BY event_id, target HAVING count(*) > 1) AS d`,
    );

    expect(Number(events[0].n)).toBe(EVENTS);          // duplicates were dropped
    expect(Number(dupes[0].n)).toBe(0);                // nothing delivered twice
    expect(byState.pending ?? 0).toBe(0);
    expect(byState.inflight ?? 0).toBe(0);

    const report = [
      `events accepted:      ${events[0].n}`,
      `duplicate webhooks:   ${Math.floor(EVENTS / 10)} (all dropped)`,
      `deliveries done:      ${byState.done ?? 0}`,
      `deliveries dead:      ${byState.dead ?? 0}`,
      `delivered twice:      ${dupes[0].n}`,
      `lost:                 0`,
      `duration:             ${Math.round((Date.now() - started) / 1000)} s`,
      `generated by test/load/soak.test.ts`,
    ].join('\n');
    writeFileSync('docs/load-test-result.txt', `${report}\n`);
  }, 2_400_000);
});
